# One-dimensional array in Python

## 1.1 Khởi tạo mảng 1 chiều

In [2]:
import numpy as np
x = np.array([1, 2, 3])
x

array([1, 2, 3])

### Bài tập: Khởi tạo một vector x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].

In [4]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 1.2. Kiểu dữ liệu của mảng

In [5]:
import numpy as np
a = np.array([1, 2])
print(type(a[0]))

<class 'numpy.int64'>


In [6]:
a = np.array([1, 2], dtype = np.float64)
print(type(a[0]))

<class 'numpy.float64'>


## 1.3. Khởi tạo các mảng một chiều đặc biệt

In [8]:
import numpy as np
np.zeros(3)

array([1., 1., 1., 1., 1.])

In [9]:
import numpy as np
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
import numpy as np
np.arange(3)

array([0, 1, 2])

In [11]:
import numpy as np
np.arange(3, 6)

array([3, 4, 5])

In [ ]:
import numpy as np
np.arange(0, 1, 0.1)

### Bài tập 1: Xây dựng mảng các luỹ thừa của 2 nhỏ hơn 1025, bao gồm cả 1 = 2**0. Gợi ý: Nếu a là một mảng và b là một số thì b**a sẽ trả về một mảng cùng kích thước với a mà phần tử có chỉ số i bằng b**a[i], với ** là toán tử luỹ thừa.

In [14]:
import numpy as np

print(np.arange(1, 1026) ** 2)

[      1       4       9 ... 1046529 1048576 1050625]


### Bài tập 2: Xây dựng mảng gồm 10 phần tử, trong đó 9 phần tử đầu bằng 3, phần tử cuối cùng bằng 1.5.

In [15]:
import numpy as np

arr = np.full(10, 3)
arr[-1] = 1.5
print(arr)

[3 3 3 3 3 3 3 3 3 1]


## 1.4. Truy cập mảng một chiều