## 2.1. Khởi tạo một ma trận

In [1]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


### Bài tập: Khai báo một mảng numpy hai chiều A mô tả ma trận:

In [2]:
import numpy as np
A = np.array([[[1,2,3], [4,5,6], [7,8,9]]])

print(A)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


## 2.2. Ma trận đơn vị và ma trận đường chéo

In [3]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
import numpy as np
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

### Bài tập: Với một số tự nhiên n, hãy viết hàm trả về ma trận có dạng: tức đường chéo phụ ngay dưới đường chéo chính nhận các giá trị từ 1 đến n. Các thành phần là kiểu số nguyên.

In [7]:
import numpy as np
n = int(input('Nhap so n: '))

np.diag([x for x in range(1, n+1)], k = -1)

array([[0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0]])

## 2.3. Kích thước của ma trận

In [8]:
import numpy as np 
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
A

A.shape

(3, 4)

## 2.4. Truy cập vào từng phần tử của ma trận

In [10]:
import numpy as np 
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(A)
print(A[1][2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [11]:
import numpy as np 
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(A)
print(A[1, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [16]:
import numpy as np 
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(A)
print("Line 3: ", A[2, :])
print("Column 2: ", A[:, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Line 3:  [7 8 9]
Column 2:  [2 5 8]


### Bài tập: Cho một ma trận A, viết hàm myfunc tính tổng các phần tử trên các cột có chỉ số chẵn (0, 2, 4, ...) của ma trận đó. Ví dụ:

In [2]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def myFunc(arr):
    s = 0
    for x in range(0, A.shape[1], 2):
        s += sum(arr[:, x])
    return s

myFunc(A)

30

## 2.5. Truy cập vào nhiều phần tử của ma trận